inspinia/frontend/__init__.py
# -*- coding: utf-8 -*-
from __future__ import print_function, absolute_import, division, unicode_literals

from functools import wraps

from flask import render_template, request
from werkzeug.exceptions import InternalServerError, NotFound, Unauthorized, Forbidden

from . import assets, admin
from .. import factory, tasks


def create_app(settings_override=None):
    app = factory.create_app(__name__, __path__, settings_override)

    # Configure the jinja2 environment
    app.jinja_env.trim_blocks = True
    app.jinja_env.lstrip_blocks = True
    app.jinja_env.auto_reload = app.config.get('DEBUG', True)

    # Init assets
    assets.init_app(app)

    # Init admin
    admin.init_app(app)

    # Setup security async email send
    security_ctx = app.extensions['security']

    @security_ctx.send_mail_task
    def delay_security_email(msg):  # pylint: disable=unused-variable
        tasks.send_security_email.delay(msg)

    # Register custom error handlers
    if not app.debug:
        for ex in [InternalServerError, NotFound, Unauthorized, Forbidden]:
            app.errorhandler(ex.code)(handle_error)

    return app


def handle_error(error):
    return render_template('error.html', error=error, return_url=request.args.get('return_url'))


def route(blueprint, *args, **kwargs):
    kwargs.setdefault('strict_slashes', False)
    kwargs.setdefault('methods', ['GET'])

    def decorator(func):
        @blueprint.route(*args, **kwargs)
        @wraps(func)
        def wrapper(*func_args, **func_kwargs):  # pylint: disable=unused-variable
            return func(*func_args, **func_kwargs)

        return func

    return decorator

inspinia/frontend/app.py
# -*- coding: utf-8 -*-
from __future__ import print_function, absolute_import, division, unicode_literals

from flask import Blueprint, render_template
from flask_security import login_required

from . import route

bp = Blueprint('app', __name__)


@route(bp, '/')
@login_required
def index():
    return render_template('index.html')

inspinia/frontend/templates/admin_master.html
{% extends 'admin/base.html' %}

{% block head_css %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/font-awesome.min.css') }}" rel="stylesheet">
{% endblock head_css %}

{% block access_control %}
    {% if current_user.is_authenticated %}
        <div class="navbar-text btn-group pull-right">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                <i class="fa fa-user glyphicon glyphicon-user"></i>
                {% if current_user.first_name and current_user.last_name -%}
                    {{ current_user.first_name }} {{ current_user.last_name }}
                {% else -%}
                    {{ current_user.email }}
                {%- endif %}<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('app.index') }}">Landing Page</a></li>
                <li><a href="{{ url_for_security('change_password', next=admin_view.url) }}">Change Password</a></li>
                <li class="divider"></li>
                <li><a href="{{ url_for_security('logout') }}">Logout</a></li>
            </ul>
        </div>
    {% else %}
        <div class="navbar-text btn-group pull-right">
            <a href="{{ url_for_security('login') }}"><i class="fa fa-sign-in"></i> Log In</a>
        </div>
    {% endif %}
{% endblock access_control %}

inspinia/frontend/templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% block head_meta %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="{{ config['AUTHOR'] }}">
    <meta name="description" content="{{ config['DESCRIPTION'] }}">
    {% endblock %}
    <title>{% block title %}{{ config['APP_NAME'] }}{% endblock %}</title>
    {% block favicon %}
    <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
    {% endblock %}
    {% block css_vendor %}
    <!-- Vendor styles -->
    {% assets "css_vendor" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet">
    {% endassets %}
    {% endblock %}
    {% block css_plugins %}
    <!-- Plugin styles -->
    {% assets "css_plugins" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet">
    {% endassets %}
    {% endblock %}
    {% block css_app %}
    <!-- App styles -->
    {% assets "css_app" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet">
    {% endassets %}
    {% endblock %}
    {% block head_tail %}{% endblock %}
</head>
{% block body_tag %}
<body>
{% endblock %}
{% block page_body %}
    <div class="container">
      <nav class="navbar navbar-default" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          {% block brand %}
          <a class="navbar-brand" href="#">{{ config['APP_NAME'] }}</a>
          {% endblock %}
        </div>
        <!-- navbar content -->
        <div class="collapse navbar-collapse" id="admin-navbar-collapse">
          {% block main_menu %}
          {% endblock %}
          {% block menu_links %}
          {% endblock %}
          {% block access_control %}
          {% endblock %}
        </div>
      </nav>
      {% block body %}{% endblock %}
    </div>
{% endblock %}
{% block messages %}
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <ul id="messages" style="display: none">
        {% set mapping = {'message': 'success'} %}
        {% for category, message in messages %}
        <li data-category="{{ mapping.get(category, category|default('success', true)) }}">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
{% endwith %}
{% endblock %}
{% block js_vendor %}
    <!-- Vendor scripts -->
    {% assets "js_vendor" %}
    <script src="{{ ASSET_URL }}"></script>
    {% endassets %}
{% endblock %}
{% block plugin_js %}
    <!-- Plugin scripts -->
    {% assets "js_plugins" %}
    <script src="{{ ASSET_URL }}"></script>
    {% endassets %}
{% endblock %}
{% block app_js %}
    <!-- Main scripts -->
    {% assets "js_main" %}
    <script src="{{ ASSET_URL }}"></script>
    {% endassets %}
{% endblock %}
{% block tail %}{% endblock %}
</body>
</html>

inspinia/frontend/templates/error.html
{% extends 'base.html' %}

{% block title %}Error {{ error.code }} | {{ super() }}{% endblock %}
{% block page_body %}
    <h1>{{ error.code }} {{ error.name }}</h1>
    <p>
        {{ error.description }}<br/>
        <br/>
        {% if return_url %}
        <a href="{{ return_url }}">Back</a>
        {% else %}
        <a href="{{ url_for('app.index') }}">Return to Home</a>
        {% endif %}
    </p>
{% endblock %}

inspinia/frontend/templates/index.html
{% extends "base.html" %}

{% block title %}Home | {{ super() }}{% endblock %}

{% block access_control %}
    <div class="navbar-text btn-group pull-right">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <i class="fa fa-user glyphicon glyphicon-user"></i>
            {% if current_user.first_name -%}
                {{ current_user.first_name }}
            {% else -%}
                {{ current_user.email }}
            {%- endif %}<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
            {% if current_user.has_role('admin') or current_user.has_role('superuser') %}
            <li><a href="{{ url_for('admin.index') }}">Admin Control Panel</a></li>
            {% endif %}

            <li><a href="{{ url_for_security('change_password') }}">Change Password</a></li>
            <li class="divider"></li>
            <li><a href="{{ url_for_security('logout') }}">Logout</a></li>
        </ul>
    </div>
{% endblock access_control %}
{% block body %}
    <h1>Welcome to {{ config['APP_NAME'] }}!</h1>
{% endblock %}